---
- hosts: chaperone
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - { role: jdatx.chaperone-prereqs, when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') }
